package com.YassineGroup.controller;

import com.YassineGroup.model.Fahrt;
import com.YassineGroup.model.User;
import com.YassineGroup.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import javax.servlet.http.HttpServletRequest;
import java.util.HashSet;
import java.util.Set;

@Controller
public class UserCotroller {

    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    UserService userService;
//    @Autowired
//    FahrtService fahrtService;

    public UserCotroller(UserService userService) {
        this.userService = userService;
    }

    @GetMapping("/")
    public String welcomeHome(Model model) {
        model.addAttribute("user", new User());
        return "index";
    }

    @GetMapping("/register")
    public String registerHome(Model model) {
        model.addAttribute("user", new User());
        return "registrieren";
    }

    @PostMapping("/register")
    public String formSubmit(@ModelAttribute("user") User user, Model modelAndView) {

        User existingUser = userService.findUserByEmail(user.getEmail());

        if (existingUser != null) {

            modelAndView.addAttribute("message", "This email already exists!");
            modelAndView.addAttribute("register");

            System.out.println("schon hier");
        } else {
            userService.saveUser(user);
            modelAndView.addAttribute("message", "Sie haben sich erfolgreich registriert");
            modelAndView.addAttribute("register");
        }

        System.out.println("Hello: " + user.getEmail());

        return "register";
    }

    @GetMapping("/loggin")
    public String loginHome(Model model) {
        model.addAttribute("user", new User());
        return "loggin";
    }

    @RequestMapping("/login-user")
    public String loginUser(@ModelAttribute User user, HttpServletRequest request, Model model) {
        System.out.println(user.getEmail() + " " + user.getPassword() + " " + user.getUsername());

        User existingUser = userService.findUserByUsernameAndPassword(user.getUsername(), user.getPassword());

        if (existingUser != null) {
            System.out.println("das ist richtig");
            model.addAttribute("message", "Sie sind eingeloggt!");
            return "mainIndex";
        } else {
            model.addAttribute("message", "Invalid Username or Password! ");
            System.out.println("Nein nLeider hejt nicht");
            return "error";
        }
    }

    @GetMapping("/fahrtt")
    public String testfahrt(Model model) {

        User user = new User("name","lastname","username","yassine@yahoo.de","password");

        Set<Fahrt> fahr = new HashSet<Fahrt>();

// Create Comments
        Fahrt fahrt = new Fahrt("fromt", "tot", "dateez", 25, "placte", user);

        Fahrt fahrt1 = new Fahrt("from", "to", "datee", 25, "plact", user);
        fahr.add(fahrt);
        fahr.add(fahrt1);
        user.setFahrt(fahr);
        fahrt.setUser(user);

        System.out.println(fahrt.toString());

        System.out.println("Ich bin drin");
        System.out.println(user.getFahrt().size());

        user.getFahrt().add(fahrt);

        System.out.println("Ich bin drin");

        userService.saveUser(user);

        System.out.println("Ich bin drin saved");
        System.out.println(user.getFahrt().toString());
        System.out.println("Ich bin drin show");

        return "test";
    }

    @GetMapping("/showFahrt")
    public String showfahr(Model model) {
        model.addAttribute("fahrt", new Fahrt());
        return "fahrtHunzufuegen";
    }

//    @GetMapping("/addFahrt")
//    public String addFahr(@ModelAttribute User user, HttpServletRequest request, Model model) {
//        model.addAttribute("fahrt", new Fahrt());
//        return "fahrtHunzufuegen";
//    }

    @PostMapping("/addFahrt")
    public String addFahr(@ModelAttribute("fahrt") Fahrt fahrt, Model modelAndView) {
        Set<Fahrt> fahr = new HashSet<Fahrt>();
        fahr.add(fahrt);
        fahrt.getUser().setFahrt(fahr);
        System.out.println("alles ist Richtig");

//        User existingUser = userService.findUserByEmail(user.getEmail());
//
//        if (existingUser != null) {
//
//            modelAndView.addAttribute("message", "This email already exists!");
//            modelAndView.addAttribute("register");
//
//            System.out.println("schon hier");
//        } else {
//            userService.saveUser(user);
//            modelAndView.addAttribute("message", "Sie haben sich erfolgreich registriert ");
//            modelAndView.addAttribute("register");
//        }
//
//        System.out.println("Hello: " + user.getEmail());

        return "register";
    }

    @GetMapping("/show-fahrt")
    public String sowhfahrt(@ModelAttribute User user, HttpServletRequest request, Model model) {
//        model.addAttribute("user", new User());
//        Set<Fahrt> fahr = new HashSet<Fahrt>();
//
//        User user = new User("name", "lastname", "username", "yassine@yahoo.de", "password");
////        ( "name",  "lastname",  "username",  "email_Adresse",  "password")
//
//// Create Comments
//        Fahrt fahrt = new Fahrt("fromt", "tot", "dateez", 25, "placte", user);
//        fahr.add(fahrt);
//        user.setFahrt(fahr);
//        fahrt.setOneUser(user);
//
//        System.out.println(fahrt.toString());

        System.out.println("Ich bin drin");
//        System.out.println(userService.s);

        System.out.println(user.getFahrt().toString());


//        user.getFahrt().add();


        System.out.println("Ich bin drin");

//        userService.saveUser(user);

        System.out.println("Ich bin drin");

        return "test";
    }


}
